//USER REDUCER TYPES
export const SET_AUTHENTICATED = "SET_AUTHENTICATED";
export const SET_UNAUTHENTICATED = "SET_UNAUTHENTICATED";
export const SET_USER = "SET_USER";
export const LOADING_USER = "LOADING_USER";
export const REMOVE_LOADING_USER = "REMOVE_LOADING_USER";

//UI REDUCER TYPES
export const SET_ERRORS = "SET_ERROR";
export const LOADING_UI = "LOADING_UI";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
export const STOP_LOADING_UI = "STOP_LOADING_UI";

//PROJECT REDUCER TYPES

export const SET_PROJECTS = "SET_PROJECTS";
export const SET_PROJECT = "SET_PROJECT";
export const DELETE_PROJECT = "DELETE_PROJECT";
export const CREATE_PROJECT = "CREATE_PROJECT";
export const EDIT_PROJECT = "EDIT_PROJECT";
export const LOADING_PROJECT = "LOADING_PROJECT";
